site_name: Web-programming documentation 2023-2024 
nav: 
  - Главная: index.md
  - О студенте: about.md
  - Лабораторные:
    - Лабораторная №1: labs\lab1\lab_1.md

 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


theme:
  name: material
  language: ru
  features:
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.tabs
